version: "3.9"
services:

  backend:
    container_name: "backend"
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile-dev
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: "curl localhost:3000/health"
      interval: "60s"
      timeout: "3s"
      start_period: "10s"
      retries: 3
    expose:
      - 3000
    ports:
      - "127.0.0.1:3000:3000"

  frontend:
    container_name: "web"
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile-dev
    environment:
      - NODE_ENV=production
      - PORT=8082
      - BACKEND_URL=https://api.example.com/
    expose:
      - 8082
    ports:
      - "127.0.0.1:8000:8082"
