version: "3.9"
services:

  backend:
    container_name: "backend"
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile-dev
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_DATABASE=chat
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: "curl localhost:3000/health"
      interval: "60s"
      timeout: "3s"
      start_period: "10s"
      retries: 3
    expose:
      - 3000
    ports:
      - "${BACKEND_PORT_FORWARD:-3000}:3000"

  frontend:
    container_name: "web"
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=8080
      #- BACKEND_URL=https://api.example.com/
    expose:
      - 8080
    ports:
      - "${WEB_PORT_FORWARD:-8080}:8080"
