services:

  backend:
    container_name: "backend"
    image: athlon1600/chat-api:latest
#    build:
#      context: .
#      dockerfile: ./apps/server/Dockerfile
#      target: prod
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_DATABASE=chat
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: "curl localhost:3000/health"
      interval: "60s"
      timeout: "3s"
      start_period: "10s"
      retries: 3
    ports:
      - "${BACKEND_PORT_FORWARD:-127.0.0.1:3000}:3000"

  frontend:
    container_name: "web"
    image: athlon1600/chat-frontend:latest
#    build:
#      context: .
#      dockerfile: ./apps/frontend/Dockerfile
#      target: prod
    environment:
      - NODE_ENV=production
      #- BACKEND_URL=https://chat.proxynova.net/
    ports:
      - "${WEB_PORT_FORWARD:-127.0.0.1:8000}:8000"

  database:
    container_name: db
    image: mysql:8.0.44
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
#      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "${DOCKER_MYSQL_PORT_FORWARD:-127.0.0.1:3306}:3306"

  redis:
    container_name: 'redis'
    image: redis
    restart: always
    volumes:
      - ./docker/redis/data:/data
    ports:
      - "127.0.0.1:${REDIS_PORT:-6379}:6379"

#  adminer:
#    image: adminer
#    restart: always
#    environment:
#      - ADMINER_DEFAULT_SERVER=db
#      - ADMINER_DESIGN='nette'
#    ports:
#      - "9000:8080"
