FROM node:lts-alpine

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# to install frontend specific dependencies
COPY apps/frontend/package.json apps/frontend/package.json

## internal packages we need during installation
COPY packages ./packages

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

EXPOSE 8082

CMD npm run serve --workspace frontend
# CMD sleep 99999
