FROM node:lts-alpine

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

# Things we need during installation and build steps
COPY apps/server/package.json ./apps/server/package.json
COPY tsconfig* ./

COPY packages ./packages

ENV NODE_ENV=development

# install dependencies
RUN npm install

# TODO: breaks cache anytime changes detected
COPY . .

# generate /dist for each workspace
RUN npm run build:packages

# Build the project
RUN npm run build --workspace server

EXPOSE 3000

CMD npm run dev --workspace server
# CMD sleep 999999
